-- RIGFORGE Driver Name Builder v8.3
-- Run this in Supabase SQL Editor.

create table if not exists public.estimates (
  id bigint generated by default as identity primary key,
  estimate_no text not null unique,
  builder_type text not null,
  builder_version text not null,
  items jsonb not null default '[]'::jsonb,
  total_price integer not null default 0,
  status text not null default 'saved',
  created_at timestamptz not null default now()
);

alter table public.estimates enable row level security;

drop policy if exists "public_insert_estimates" on public.estimates;
create policy "public_insert_estimates"
on public.estimates
for insert
to anon
with check (
  builder_type = 'driver-name'
  and status = 'saved'
  and jsonb_array_length(items) between 1 and 30
  and total_price between 0 and 10000000
);

-- Customer page does not need read/update/delete access.
-- Admin access should use an authenticated admin page or Supabase dashboard.
